### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by Patarimi**
I run in the same problem as #118.
This PR seems to fix the problem.
Maybe the version number needs to be increased ?

### CODE REVIEW

**Comment by antoine-de** [comment]
I think a new version number will be needed too to be published on pypi no?

I also need this, for now I cannot publish a package depending on the new `typer` version on pypi since my packge also depend on `typer-cli` (even if `typer-cli` is only in the dev dependencies).

**Comment by glass-ships** [comment]
+1 for this fix! 

Is there anything holding it back? I'd be happy to jump in and help if need be!

**Comment by rpmcginty** [comment]
@tiangolo I can see you are hard at work to get fastapi ready for pydantic v2, so I know this could fall to the wayside. That said, I think this is a pretty clean and low stakes change. It would be really helpful to merge this to utilize the documentation generation tool.

FWIW, when using this fork as a dependency (`"typer-cli @ git+ssh://git@github.com/Patarimi/typer-cli"`), I can verify documentation tool can now be run to generate docs.

**Comment by yu-iskw** [comment]
@tiangolo I would like to relax the version constraints too. The pull request would be helpful for many typer users. We really appreciate if you could take a look at it. Thanks!

**Comment by rpmcginty** [comment]
@tiangolo would you be able to review this change?

**Comment by rpmcginty** [comment]
@tiangolo is it possible to review this?

**Comment by austin-silk** [comment]
@tiangolo Please approve this PR 🙏

**Comment by UltimateLobster** [comment]
@tiangolo Considering the small size of the changes and the fact that it blocks using the newest versions of typer. we'd appreciate  it if you could review this PR 🙏

**Comment by vitorquintanilha** [comment]
+1

**Comment by fritz-astronomer** [comment]
+1

**Comment by glass-ships** [comment]
6 months later, no word at all... 
Any updates one way or another?

**Comment by Patarimi** [comment]
I found this [repo](https://github.com/bruce-szalwinski/mkdocs-typer). It is actively maintains and offer more functionality than typer-cli.

**Comment by trymzet** [comment]
Bumping, @tiangolo this seems like a trivial merge. BTW maybe add some more maintainers to the project so it doesn't die?

**Comment by begemotik** [comment]
Very sad seeing it in a hanging state.
Another try, @tiangolo hope you could find some time to review it.

**Comment by gianfrancodemarco** [comment]
Bump!

**Comment by vjeeva** [comment]
+1 please @tiangolo!

**Comment by sixdimensionalarray** [comment]
+1 @tiangolo thank you

**Comment by PieterBunnenberg** [comment]
@tiangolo Please merge this change to keep compatibility with typer 0.9.0. We really want to migrate to typer 0.9.0, but this blocks us...

**Comment by PieterBunnenberg** [comment]
I created a discussion for this issue as well: https://github.com/tiangolo/typer-cli/discussions/134

**Comment by tiangolo** [comment]
Thanks @Patarimi and everyone for the discussion here! :coffee: 

Now `typer-cli` is integrated into `typer` itself. :rocket: 

You no longer need (nor should) install `typer-cli`, instead install `typer`, and that's it, you get the `typer` command and everything.

And all the code is always in sync and up to date with the rest of Typer, etc. :tada: 

---

Meanwhile, and just for compatibility, the same Typer repo also publishes the PyPI package `typer-cli` with exactly the same version as Typer, but the new `typer-cli` PyPI package (versions `0.12.1`+) doesn't have anything, it just requires `typer`.

And the new versions of `typer` include the `typer` command, and the tools to run scripts, generate docs, etc.

As this repo is no longer relevant, I will archive it soon, everything is now in https://github.com/tiangolo/typer.

Given that, I'll close this one, thanks all! :cake:

**Pull request closed without merging**
